# Site settings
author: Adjoa N.
title: Adjoa's Flatiron School Blog
header-img: img/home-bg.png
email: adjoaan@gmail.com
copyright_name: Adjoa N.
description: > # this means to ignore newlines until "baseurl:"
  Welcome To My Blog!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  AANtoso

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
